### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by yuntas** [yasuyuky/SublimeMozcInput#2]
sorry,

This [link](http://download.opensuse.org/repositories/home:/sawaa/) is already broken...

What should I do ?

**Comment by yasuyuky** [comment]
The document is too old...

mozc_emacs_helper is included in [original mozc source](https://github.com/google/mozc)
So you can build it from source.

If you want to use rpm, you may find it [here](http://rpmfind.net/linux/rpm2html/search.php?query=mozc&submit=Search+...&system=&arch=)

Pull Request for the document is definitely welcome :wink:

**Comment by yuntas** [comment]
Thank you very much, Mr. @yasuyuky

**Comment by yasuyuky** [comment]
You're welcome :+1:
